import MultiLayerParallax from "@/components/parallax/MultiLayerParallax";
import "./globals.css";
import { Outfit } from "next/font/google";

const mont = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Parallax",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mont.className}>
        {/* <MultiLayerParallax /> */}
        {children}
      </body>
    </html>
  );
}
